directories:
  output: release
  buildResources: build
appId: com.example.electronnotificationapp
productName: ElectronNotificationApp
files:
  - filter:
      - dist/**/*
      - src/icon.png
win:
  target:
    - nsis
linux:
  category: Utility
electronVersion: 31.3.1
